version: "3"
services:
  db:
    container_name: mysql-8-LpRenovso
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yoo
      MYSQL_DATABASE: bddlprenovso
      MYSQL_USER: groupe1
      MYSQL_PASSWORD: yoo
    volumes:
      - ./dbdata:/var/lib/mysql
  phpmyadmin:
    container_name: pma-8-LpRenovso
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - db
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8080"
#    environment:
#      ADMINER_DEFAULT_SERVER: db
#      ADMINER_DESIGN: "lucas-sandery"
#    links:
#      - db
volumes:
  dbdata:version: "3.8"
services:
  database:
    container_name: LP_Renovso-database
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./var/dbdata:/var/lib/mysql
  phpmyadmin:
    container_name: LP_Renovso-pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - database
  mailer:
    container_name: LP_Renovso-mailer
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
volumes:
  dbdata: